config/routes.rb
Rails.application.routes.draw do

  post 'products.user.username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post 'products.user.username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  
  get 'products/feed'
  get 'users/show'

  resources :products
  resources :charges
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  root 'products#index'

  resources :conversations do
    resources :messages
   end

end

app/models/product.rb
class Product < ApplicationRecord
    validates :user_id, presence: true
    
    belongs_to :user
    has_one_attached :image
    #resourcify  <-- This is makes Product model a resource for

    scope :of_followed_users, -> (following_users) { where user_id: following_users }

    def can_change?(user)
        self.user == user || user.has_role?(:admin)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order('created_at DESC')
  end
  #logic for feed creating a unique user feed from other followed users
  def feed
    @products = Product.of_followed_users(current_user.following).order('created_at DESC')
  end
  
  # GET /products/1
  # GET /products/1.json
  def show
  end
  
  # GET /products/new
  def new
    @product = Product.new
    
  end
  
  # GET /products/1/edit
  def edit
  end
  
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.image.attach(product_params[:image])
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
    
  end
  
  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end
  
  def check_permissions
    if !@products.can_change?(current_user)
      redirect_to(request.refferer || root_path, :alert => "You are not Authorised")
    end
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :image, :available, :description, :price)
    
  end
  #stripe stuff
  
  
end

app/helpers/products_helper.rb
module ProductsHelper
    def current_user_is_following(current_user_id, followed_user_id)
        if Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
            return true
        end
        return false
    end   
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
<%# the error was an empty feild so a nil check was added %>
  <% if product != nil%>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

    <div class="field">
      <%= form.label :name%>
      <%= form.text_area :name%>
    </div>

    <div class="field">
      <%= form.label :image%>
      <%= form.file_field :image%>
    </div>

    <div class="field">
      <%= form.label :description%>
      <%= form.text_area :description%>
    </div>

    <div class="field">
      <%= form.label :available%>
      <%= form.check_box :available %>
    </div>

    <div class="field">
      <%= form.label :price%>
      <%= form.number_field :price,  :class => 'text_field' %> 
    </div>


  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/feed.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<!-- user Sign off link -->
<%= link_to "Log Out", destroy_user_session_path, :method => :delete %>  | 
<%= link_to 'New Product', new_product_path %> |
<%= link_to 'Conversations', conversations_path %> |
<%= link_to 'Followed Feed', products_feed_path%> |
<%= link_to 'Your Profile', users_show_path%>
<hr>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <div class="row">
    <% @products.each do |product| %>
      <div class="card col-4" style="width: 18rem;">
        <%= cl_image_tag(product.image.key, class: "card-img-top")%>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %> </h5>
          <p class="card-text"><%= product.description %><p>
            
          <% if product.available == true %>
            Available <%= product.price %>  
          <% end %>
            
          <% if product.user_id == current_user.id%>
            <%# Rolify logic for user authorisation can go here %>
            <%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary"  %>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <%else%>
            <% if current_user_is_following(product.user_id, current_user.id)%>
              <%=link_to 'Following', unfollow_user_path(:following_id => product.user_id),
                                  class: 'btn btn-primary',
                                  id: 'unfollow-button',
                                  remote: true,
                                  method: :post%>
            <%else%>
            <%= link_to 'Follow', follow_user_path(:following_id => product.user_id),
                                  remote: true,
                                  class: 'btn btn-primary',
                                  id: 'follow-button',
                                  method: :post %>
            <%end%>
          <%end%>

        </div>
      </div>
      
    <%end%>
</div>   
<br>

app/views/products/follow_feed.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  
  <div>
    <% @products.each do |product| if product  %>
        <%= cl_image_tag(product.image.key) if product.image != nil %>
        <%= product.name%>
        <%= link_to 'Show', product %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      
    <% end %>
  </div>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/follow_user.js.erb
$('#follow-button').attr('class', 'btn unfollow-button')
                   .text('Following')
                   .attr('href', "/<%= @user.username %>/unfollow_user")
                   .attr('id', 'unfollow-button');

app/views/products/index.html.erb
<h1>Products</h1>
<!-- user Sign off link -->
<%= link_to "Log Out", destroy_user_session_path, :method => :delete %>  | 
<%= link_to 'New Product', new_product_path %> |
<%= link_to 'Conversations', conversations_path %> |
<%= link_to 'Followed Feed', products_feed_path%> |
<%= link_to 'Your Profile', users_show_path%>
 <hr>
  <div class="row">
    <% @products.each do |product| %>
      <div class="card col-4" style="width: 18rem;">
        <%= cl_image_tag(product.image.key, class: "card-img-top")%>
        <div class="card-body">
          <p class="card-text"><%= product.user.username %><p>
          <h5 class="card-title"><%= product.name %> </h5>

          <p class="card-text"><%= product.description %></p>

          <% if product.available == true %>

            Available : $ <%= product.price %> <br>
            <% if product.user_id != current_user.id %>
            <%= form_tag charges_path do %>
              <article>
                <% if flash[:error].present? %>
                  <div id="error_explanation">
                    <p><%= flash[:error] %></p>
                  </div>
                <% end %>
              </article>

              
              <%= hidden_field_tag 'price', product.price %>
              <%= hidden_field_tag 'product_id', product.id %>

              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" 
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>" 
                data-description="<%= product.name %>" 
                data-label="Buy with card" 
                data-email="<%= current_user.email %>" 
                data-amount="<%= (product.price) * 100 %>" 
                data-currency="aud" 
                data-locale="en"></script>
                <% end %>
            <% end %>
          <% end %>
            
          <% if product.user_id == current_user.id%>
            <%# Rolify logic for user authorisation can go here %>
            <%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary"  %>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <%else%>
            <% if current_user_is_following(current_user.id, product.user_id) == true%>
              <%=link_to 'Following', unfollow_user_path(:following_id => product.user_id),
                                  class: 'btn btn-primary',
                                  id: 'unfollow-button',
                                  remote: true,
                                  method: :post%>
            <%else%>
              <%= link_to 'Follow', follow_user_path(:following_id => product.user_id),
                                  remote: true,
                                  class: 'btn btn-primary',
                                  id: 'follow-button',
                                  method: :post %>
            <%end%>
          <%end%>
        
        </div>
      </div>
      
    <%end%>
</div>   
<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= link_to 'Back', root_path %>
<p>
    <strong>Name:</strong>
    <%= @product.name %>
</p>

<p>
    <%= image_tag @product.image%>
</p>

<%# copy pasted from views/_forms %>


<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <%# changed amount to price (line 13) - makes more sense %>
    <label class="amount">
      <span>Price: $ <%= @product.price %></span>
    </label>
  </article>
  <%if @product.user_id != current_user.id%>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Selected item"
          data-amount="500"
          data-locale="auto"></script>
  <% end %>
<% end %>

app/views/products/unfollow_user.js.erb
$('#unfollow-button').text('Follow')
                     .attr('class', 'btn follow-button')
                     .attr('href', "/<%= @user.username %>/follow_user")
                     .attr('id', 'follow-button');