config/routes.rb
Rails.application.routes.draw do

  post 'products.user.username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post 'products.user.username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  
  get 'products/feed'
  get 'users/show'

  resources :products
  resources :charges
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  root 'products#index'

  resources :conversations do
    resources :messages
   end

end

app/models/charge.rb
class Charge < ApplicationRecord
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
    end
    #Shows credit card form using checkout
    #created the actual charges by calling api
    def create
      # Amount in cents
      @amount = params[:price].to_i * 100
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'aud'
      )
    
      set_available_to_false(params[:product_id])
      add_user_balance(params[:price])
      redirect_to root_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

    private
    def set_available_to_false(product_id)
      product = Product.find(product_id)
      product.available = false
      product.save
    end

    def add_user_balance(price)
      user = Product.find(params[:product_id]).user
      user.balance = user.balance + price.to_i
      user.save
    end
        
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= form_with(model: charge, local: true) do |form| %>
  <% if charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% charge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$</strong>!</h2>

app/views/charges/edit.html.erb
<h1>Editing Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Charges</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New Charge</h1>


<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <%# changed amount to price (line 13) - makes more sense %>
    <label class="amount">
      <span>Price: $</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A selected item"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>